- name: 创建同步文件夹
  file:
    path: $HOME/backup
    state: directory
    mode: '0666'

- name: 上传恢复数据脚本
  copy:
    src: restore.sh
    dest: $HOME/backup/restore.sh
    mode: '0755'


- name: 判断是否安装 {{backup_soft_name}}
  shell: |
        # 检查 {{backup_soft_name}} 容器是否在运行
        container=$(docker ps -a --filter "name={{backup_soft_name}}" --format "{% raw %}{{.Names}}{% endraw %}")
        if [[ "$container" == "{{backup_soft_name}}" ]]; then
            echo "{{backup_soft_name}} 容器正在运行，停止容器..."
            docker stop {{backup_soft_name}}
            echo "删除 {{backup_soft_name}} 容器."
            docker rm  {{backup_soft_name}}
        fi
        mkdir -p {{backup_soft_name}}

- name: 运行恢复数据安装脚本
  shell: $HOME/backup/restore.sh {{localFilePath}} {{oneDrivePath}} {{client_id}} {{client_secret}} {{tenant_id}} {{backup_soft_name}}
  register: my_output # <- Registers the command output.
  changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.

- name: 运行 {{backup_soft_name}}
  shell: docker compose -f $HOME/{{backup_soft_name}}/docker-compose.yaml up -d
  register: my_output # <- Registers the command output.
  changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.

- name: 运行备份 {{backup_soft_name}}
  shell: docker compose -f $HOME/{{backup_soft_name}}/docker-compose.yaml up -d
  register: my_output # <- Registers the command output.
  changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.
