- name: 创建同步文件夹
  file:
    path: $HOME/cronbackup
    state: directory
    mode: '0666'

- name: 上传恢复数据脚本
  copy:
    src: restore.sh
    dest: $HOME/backup/restore.sh
    mode: '0755'

- name: 恢复 {{backup_soft_name}} 数据
  shell: $HOME/backup/restore.sh -e {{client_id}},{{client_secret}},{{tenant_id}},{{localFilePath}},{{oneDrivePath}},{{backup_soft_name}}
  register: my_output # <- Registers the command output.
  changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.