name: ansible
on: push

jobs:
   job1:
      runs-on: ubuntu-latest
      container:
       image: honyua/ansible_py:v0.1
      name: echo
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: run ansible playbooks
        run: pwd && ls && chmod u+x,g-wx,o-wx ../ansible && ansible-playbook playbooks.yaml -vv --tags installdocker
