name: ansible
on:
  push:
    paths-ignore:
      - 'dockerfile'
      - 'ansible_docker_build.yml'

jobs:
   job1:
      runs-on: ubuntu-latest
      container:
       image: honyua/ansible_py:v0.1
      name: 运行ansible
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: run ansible playbooks
        run: pwd && ls && chmod u+x,g-wx,o-wx ../ansible && chmod 0400 ./config/.ssh/id_rsa && ansible-playbook playbooks.yaml -vv --tags installdocker
