name: ansible_input
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      host:
        description: host ip address or hostname
        required: true
      password:
        description: user root password
        required: true
jobs:
   job2:
      runs-on: ubuntu-latest
      container:
       image: honyua/ansible_py:v0.1
      name: 运行ansible
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: run ansible playbooks
      #   run: pwd && ls && chmod u+x,g-wx,o-wx ../ansible && chmod 0400 ./config/.ssh/id_rsa && ansible-playbook playbooks.yaml -vv --tags installdocker
      - name: 生成 host文件
        run: echo hello
      - name: check host file
        run: cat hosts
