name: ansible_input
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Select the source branch"
        required: false
        default: "openwrt-main"
        type: choice
        options:
          - openwrt-main
          - lede-master
          - immortalwrt-master
jobs:
   job2:
      runs-on: ubuntu-latest
      container:
       image: honyua/ansible_py:v0.1
      name: 运行ansible
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: run ansible playbooks
      #   run: pwd && ls && chmod u+x,g-wx,o-wx ../ansible && chmod 0400 ./config/.ssh/id_rsa && ansible-playbook playbooks.yaml -vv --tags installdocker
      - name: 生成 host文件
        run: echo hello
      - name: check host file
        run: cat hosts
